### ISSUE TITLE
Handling multiple projects

### ISSUE THREAD

**Issue by mat-mcloughlin** [ligershark/Kulture#16]
Currently have a test lib and a class lib. 

Just wondering about the functionality to either build or run either of the projects from root?

**Comment by shirhatti** [comment]
RIght now the way I have it set up is it keeps going up the directory structure till it finds a `project.json` file.

Right now the project that builds will be whichever project the selected file belongs to

A possible approach will be to use the a `*.sublime-project` file (#13). I personally think that this way is not the right approach and I'm open to further discussion

cc @sayedihashimi

**Comment by sayedihashimi** [comment]
I've made changes in commits related to #22 which should help this. Current logic: it will look at folder of the file being edited for project.Jason. If not found it will look up until it os found. Can you try out the version in master?

I'll close this now. For any follow up please use #22.

**Comment by mat-mcloughlin** [comment]
Thanks,

I'll take a look later today :)
