### ISSUE TITLE
Sublime for windows: kpm restore cannot be found

### ISSUE THREAD

**Issue by lnaie** [ligershark/Kulture#24]
In windows 8.1, when running 'kpm restore', power shell opens up but is not able to find kpm:

kpm : The term 'kpm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
- kpm restore
- ~~~
  - CategoryInfo          : ObjectNotFound: (kpm:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

Anything else that should be done extra for sublime on windows?

Thx

**Comment by lnaie** [comment]
Figured it out.
Somehow "C:\Users[user_name].kre\run-once.cmd" fails to update the Path environment var. Thus powershell cannot find kpm.cmd, which right now is in "C:\Users[user_name].kre\packages\KRE-svr50-x86.1.0.0-alpha3\bin"
I have run run-once.cmd manually without success.

**Comment by sayedihashimi** [comment]
Can you try with the latest build in the master branch and let us know if it repros there? See the [readme](https://github.com/ligershark/Kulture) under Manual Install for more info.

**Comment by sayedihashimi** [comment]
@lnaie are you saying there is a bug run-once.cmd? If so we should file that in another repo I'm not sure which one but can find out.

**Comment by lnaie** [comment]
Yes, I think somehow the Path var is not updated after a new package, e.g. KRE-svr50-x86.1.0.0-alpha3, has been downloaded. If so, then kpm tool is nowhere to be found by this command:
Package Control: No updated packages
['C:\Users\[user_name]\AppData\Roaming\Sublime Text 3\Packages\Kulture\PS.bat', 'kpm restore']

Or maybe you could use %KRE_HOME% in PS.ps1

**Comment by sayedihashimi** [comment]
Ok I'm guessing this may be a first time install bug. If so perhaps the best way to test for it is to create a new vm (_perhaps new user is ok, not sure_) and try from scratch. Sublime should be running when installing kvm. Once we can get a repro I can start investigating the fix.

**Comment by sayedihashimi** [comment]
I tried it on Windows 8.1 for a user which had never installed kvm command line tools and there were no errors. Is there anything unique about your setup? Do you have any special characters or spaces in your My Documents path or username? Any other thing we can try so that we can get a repro?

**Comment by ivaylo-botusharov** [comment]
I followed the installation instructions from the Sublime Kulture website and received the same error: 

 The term 'kpm' is not recognized as the name of a cmdlet,...

(I am running Windows 8.0)
Finally, I fixed the issue by manually adding: C:\Users\MyUsername.kre\packages\KRE-CLR-x86.1.0.0-alpha4\bin to (Environment Variables) Path in Windows. Hope this information is helpful.

**Comment by sayedihashimi** [comment]
@encounter12 @lnaie after you run through the instructions to install the asp.net command line tools is kpm available from a new prompt? If not that is an issue with the asp.net command line tools so if you could open a new issue at https://github.com/aspnet/home that would be ideal.

Kulture is moving to https://github.com/OmniSharp/Kulture. If it turns out that kpm is available in a new prompt then it is likely a Kulture issue, could you open a new issue at https://github.com/OmniSharp/Kulture/issues. Closing this issue now.
