### ISSUE TITLE
Is Sublime Text 3 the right target editor?

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/Kulture#26]
A few of us met today to discuss Kulture and one of the questions that came up was, is Sublime Text 3 the correct editor for this effort?

For some background we'd like to enable ASP.NET vNext on all platforms and with all tools. We would like to create an experience for a single third party editor/tool which is popular on Mac. That implementation would ensure that we have all the features we need in ASP.NET vNext and it will serve as a model for how others can develop similar experiences.

We chose Sublime Text because it seems like it's a widely used editor for many web developers and has a good (_heavily used_) plugin ecosystem. We chose Sublime Text 3 because targeting Sublime Text 2 and then upgrading that code for 3 would be very costly. Supporting two different versions would have been difficult as well.

The question of Sublime came up primarily because it is not open source. Ideally we could support an open source tool instead of a close source tool which requires a license fee.

Is there any open source editor which is as popular as Sublime is on Mac? Any links to data on this would be helpful.

Let's discuss here. In the meantime let's keep the momentum we have and continue to see how far we can get with Sublime Text 3.

**Comment by madskristensen** [comment]
Rumors are that SublimeText 3 will be open source after being finalized and accept contributions going forward after that

**Comment by sayedihashimi** [comment]
@madskristensen that is a good rumor. Thanks for sharing I had not heard that.

**Comment by phillip-haydon** [comment]
+1 Sublime Text 3

I would suggest Atom but they seem reluctant to fix bugs.

**Comment by luisrudge** [comment]
Brackets! :heart:

**Comment by jchannon** [comment]
I use Brackets for nodejs development with a set of extensions/plugins that makes it very IDE like. Their documentation on creating extensions/plugins is pretty good compared to Sublime which has minimal info. Brackets also has a specific `hintProvider` for intellisense etc. https://github.com/adobe/brackets/wiki/How-to-write-extensions#extending-specific-brackets-features 

I'm not religious about the editor I use though so whatever is chosen is fine by me :smile:

**Comment by ghost** [comment]
If Sublime goes OS then that seems like a good choice. But given the lack of progress on it recently would it be a risk if it didn't get open sourced?

**Comment by luisrudge** [comment]
@mathew-mcloughlin i agree. Not only that, but the brackets and atom communities are growing constantly. They're pretty active and all the extensibility points are there. I like brackets better because it's written in javascript instead of coffee script like atom.

**Comment by jchannon** [comment]
@luisrudge good point!

**Comment by ThatRendle** [comment]
+1 for Brackets, which is excellent: fully supported by a company with plenty of resources to throw at it; developed in the open; and -- at present -- faster and more stable than Atom.

The other thing that might push in its favour is that it incorporates Node for plug-ins, and that might make it possible to use Edge.js to call into .NET components (and of course Edge also works with Mono).

**Comment by phillip-haydon** [comment]
Sounds like I need to give Brackets a try.

I tried Atom but the devs are hopeless so I went back to Sublime.

**Comment by ThatRendle** [comment]
I've been using Brackets for all my client-side code lately. If it worked with ASP.NET vNext I would use it even more.

**Comment by jchannon** [comment]
I spent an hour and got this far with brackets (see screenshot) so I think
it's doable https://github.com/ligershark/Kulture/issues/27

**Comment by e00dan** [comment]
Go with Brackets, it's plugins are powerful, it is open source, has nice UI and works well also on Linux.

**Comment by sayedihashimi** [comment]
Thanks for all the feedback.

We are prioritizing Sublime because _that's where the users are_ not because the plugin system is easy. I checked https://sublime.wbond.net/browse/popular and there are several plugins which have > 100k downloads. Does brackets/atom.io have similar number of users for editor/plugins as Sublime has?

With that said there is nothing stopping us from working on another editor at the same time. IMO it's best to consolidate efforts initially, but if anyone is really passionate about a specific editor then let's consider it. I'm open for ideas.

**Comment by luisrudge** [comment]
That's where the users are - **for now.**
We gonna have to try to anticipate where they'll be a year from now.
There's lot of unanswered questions about the future of sublime text, but the roadmap for atom or brackets are there and the community too.

**Comment by nosami** [comment]
Looks like brackets / atom work will continue regardless - https://twitter.com/jchannon/status/507624151650021378

As for me, you can prise emacs from my cold dead hands :)

**Comment by sayedihashimi** [comment]
@luisrudge the future of Sublime Text is fine the author has announced commitment to a new version and long delays are typical for releases. I'm hoping that within a year we will see a story for ASP.NET vNext on brackets & atom.io.

**Comment by nosami** [comment]
It doesn't seem good form to be promoting a proprietary product. I doubt that you would get as many contributions as you would for an OSS editor. I know that I personally wouldn't want to spend my time working on Sublime.

As for Atom.IO, I'm pretty sure that C# support will be there within a week. Client side support is trivial if the editor has a good API / documentation.

**Comment by sayedihashimi** [comment]
OK thanks. It sounds like there's a lot of interest in brackets amongst this group.

@nosami the work you're doing in OmniSharp will help all of the efforts.

Should we create a `KultureBrackets` repo and get that effort started? 

@jchannon if you could help me with the changes for OmniSharpSublime I'd really appreciate that. Even if you could walk me through it that would be great.

**Comment by shanselman** [comment]
The deal is this. First, I agree that it would be better to get support for an OSS editor first. I was actually the first to broach this issue internally with Sayed. 

But - Sublime is ahead as far as number of users by an order of magnitude or more. 

Let's focus on the generic C# brain and intellisense service and the editor hooks will come.  

## 

Scott Hanselman

-----Original Message-----

**Comment by jchannon** [comment]
@sayedihashimi yup no worries, happy to help :smile:

**Comment by ThatRendle** [comment]
@shanselman There's only one possible solution: **open-source Visual Studio**.

Make it so.

**Comment by jchannon** [comment]
Here's an interesting page that shows Github forks/stars usage for text editors - https://github.com/showcases/text-editors

**Comment by nathanboktae** [comment]
-1 for Brackets. Adobe is overly focused on just replacing dreamweaver. It's for front end developers that work on static files. Using it with a real webapp with templates, where .html files aren't served but clean URLs are (because it's not the 90s!), bundling, source maps, etc it just falls over. It wouldn't even autocomplete my less variables out of the box. Not to mention full stack people like us that want to do their server code in the same editor, or open a file over a couple of megs... bleh. 

Sublime is bigger than Atom & Brackets for a reason - it's better.

(excuse the necromancy)

**Comment by sayedihashimi** [comment]
The project has moved to https://github.com/OmniSharp/Kulture
