### ISSUE TITLE
project.json IntelliSense

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/Kulture#27]
We have an implementation of completions in project.json in the `autocomplete` branch, but that functionality is limited to the top 100 NuGet packages so it's not very useful. We should re-implement that.

We should enable the following features.
- [ ] Complete package name
- [ ] Complete package versions
- [ ] Basic IntelliSense for the entire file
### Ideas on design

For completing package name we have the following options.
1. When a user enters `CMD + Spacebar` to query nuget.org/myget.org to get the names of packages that start with the previously entered text
2. When a user enters `CMD + Spacebar` we look up available package names in a file which is shipped with Kulture
   1 Have a combined approach where we have an index of package names, and when there is no hit on that cache we query nuget.org/myget.org

I like the idea of having a cache, but I'm not sure if it's required. Perhaps directly querying nuget.org/myget.org is good enough. Maybe we could prototype that and see what the experience feels like. If it is too slow then we can start adding caching/using an index.

**Comment by jchannon** [comment]
What does Package Control Manager do in VS? I believe that queries NuGet when you press `Install-Package Nan + TAB` to find Nancy?

**Comment by sayedihashimi** [comment]
@jchannon yes that's correct. It also reads the directory for package 📦 names so maybe we can do the same. That's a great idea 💡.

cc @mkristensen

**Comment by jchannon** [comment]
:blush:

**Comment by sayedihashimi** [comment]
@jchannon in VS we use the list of package names for automatic completion of package names. So it shows suggestions as you type. ~~I just checked Sublime and I'm not sure if they have the same ability. It seems like completions are just triggered with `CTRL+.`~~.

Update: looks like I was wrong. I'm still looking into it though.

**Comment by jchannon** [comment]
I think you _could_ do that in Sublime similar to how OmnisharpSublime plugin works.

I had a quick play with Brackets and intellisense. Their API and documentation is very good in comparison to Sublime. They have a CodeHintManager which you create your own implementation and then provide the intellisense results and decide when to show them eg/after a `.` is typed or when `Ctrl+Space` is pressed.

The docs are here http://brackets.io/docs/current/modules/editor/CodeHintManager.html

I spent an hour and hard coded the options but this is what I got

![pic](https://cloud.githubusercontent.com/assets/105126/4161366/99698f36-34cc-11e4-8f1a-52fd268a851f.png)

**Comment by sayedihashimi** [comment]
@jchannon thanks link. I haven't done much with brackets yet. Right now in Sublime I'm trying to figure out if there is a way to disable standard completions and only show completions on `CTRL+.`.

**Comment by sayedihashimi** [comment]
OK I played around a bit with Sublime completions for package names. Here is what I found.
- I couldn't distinguish from an auto completion versus an explicitly triggered one (i.e. `CTRL+.`)
- I couldn't figure out how to disable auto completions

Because of that I wasn't able to really get dynamic completions working well by calling nuget.org/myget.org on the fly.

Instead what I did was write a node script that downloads all of the package names to a file. Right now I've got the the file include as a part of the project. When the first completion is triggered the file will be loaded into memory and completions for package names are derived from that.

Could you try out the experience in the `complete-pkgnames` branch and let me know what you think? If we like this we can merge to master and figure out a way to automate updating the file that has the package names.

**Comment by jchannon** [comment]
I think you may be able to disable completions if you look at the OmniSharpSublime plugin where it does its completions. Instead of completing when you type a package name how about it only looks up when you press tab maybe or when you press CTRL + . - this all depends on if we can disable auto completions

**Comment by sayedihashimi** [comment]
Kulture is moving to https://github.com/OmniSharp/Kulture closing this now. If we should continue this conversation let's do it there.
