### ISSUE TITLE
Build fails when using CMD+B, but not 'kpm build'

### ISSUE THREAD

**Issue by bmsullivan** [ligershark/Kulture#29]
When I use the CMD+B shortcut on a newly-generated MVC project from yeoman, I get the following error messages:

```
 /Users/brian/Projects/MvcApplication1/Startup.cs(1,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Startup.cs(2,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Startup.cs(3,17): error CS0234: The type or namespace name 'Framework' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Controllers/HomeController.cs(1,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Models/User.cs(1,29): error CS0234: The type or namespace name 'DataAnnotations' does not exist in the namespace 'System.ComponentModel' (are you missing an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Startup.cs(9,31): error CS0246: The type or namespace name 'IBuilder' could not be found (are you missing a using directive or an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Controllers/HomeController.cs(6,35): error CS0246: The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Controllers/HomeController.cs(8,16): error CS0246: The type or namespace name 'IActionResult' could not be found (are you missing a using directive or an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Models/User.cs(7,10): error CS0246: The type or namespace name 'Required' could not be found (are you missing a using directive or an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Models/User.cs(8,10): error CS0246: The type or namespace name 'MinLength' could not be found (are you missing a using directive or an assembly reference?)
 /Users/brian/Projects/MvcApplication1/Controllers/HomeController.cs(10,20): error CS0103: The name 'View' does not exist in the current context

 Build failed.
     0 Warnings(s)
     11 Error(s)

 Time elapsed 00:00:01.0468637
 [Finished in 1.3s with exit code 255]
 [cmd: ['sh', '/Users/brian/Library/Application Support/Sublime Text 3/Packages/Kulture/build.sh']]
 [dir: /Users/brian/Projects/MvcApplication1]
 [path: /usr/bin:/bin:/usr/sbin:/sbin]
```

However, when I use the command palette to do a `kpm build`, it builds just fine.

Also, if I add the following to build.sh within the Kulture package, CMD+B starts to work (I got this snippet from my .bash_profile):

```
 [ -s "/Users/brian/.kre/kvm.sh" ] && . "/Users/brian/.kre/kvm/kvm.sh"
```

Is something screwed up in my environment, or does this need to be included in build.sh?

**Comment by sayedihashimi** [comment]
I made some changes in this area in the `master` branch a few days back. Would you mind tying the latest from `master` and letting me know if this is still an issue?

More details about [how to try out the latest from master](https://github.com/ligershark/Kulture/wiki/How-to-try-out-the-latest-changes-in-the-master-branch).

**Comment by bmsullivan** [comment]
@sayedihashimi - I actually encountered the problem using master as of this afternoon (9/7/2014). It doesn't look like you've made changes since then. I'm also running the newest mono K as of this afternoon, as well (build 10353, I believe), if that's important.

**Comment by matthewblott** [comment]
Same issue here as bmsullivan.

**Comment by sayedihashimi** [comment]
Could either of you help me with the fix? Since it doesn't repro for me its difficult to verify. It looks like @bmsullivan already has the fix. If someone could send a PR I'd appreciate that.

**Comment by matthewblott** [comment]
Thanks for the quick response. I recently switched to a Macbook and am not overly familiar with *nix environments but know the basics. I did spend a fair bit of time looking yesterday but to no avail but will try again later and post the results.

**Comment by bmsullivan** [comment]
PR #32 sent. Let me know if I can do anything else to help!

**Comment by jdavies322** [comment]
Hi! I'm also getting build errors while following the Getting Started instructions. Mac OS 10.7.5:

```
/Users/xxx/Home/samples/HelloWeb/Startup.cs(7,31): error CS0246: The type or namespace name 'IBuilder' could not be found (are you missing a using directive or an assembly reference?)
```

I just tried the latest from master as recommended above and it didn't resolve the problem.

**Comment by jdavies322** [comment]
Sorry, I should note that I get the above build failures whether I use the keyboard shortcut or the kpm build command.

**Comment by matthewblott** [comment]
Same, tried the latest again. I ran source kvm.sh - is that what you meant bmsullivan?

**Comment by sayedihashimi** [comment]
@jdavies322 `IBuilder` has changed to `IApplicationBuilder` in the latest versions of the runtime nuget pkgs. I have updated `yo aspnet` the other day.

Regarding build failed the change from @bmsullivan #32 is in the `master` branch. 

I'm on a plane currently so don't want to merge now but should be able to merge to `release` (_which publishes to sublime pkg manager_) later tonight.

**Comment by spboyer** [comment]
@jdavies322 quick fix, just edit Startup.cs and change IBuilder to IApplicationBuilder

**Comment by jdavies322** [comment]
Thanks **[spboyer](https://github.com/spboyer)** -- that got the samples working!

**Comment by matthewblott** [comment]
I got the samples working too. It took a lot of tinkering around as I've only starting using OSX and Mono but here's what I did:
1. Set the KVM source to get the latest dev version.

KVM_SOURCE=https://www.myget.org/f/aspnetmaster/api/v2
1. Installed the latest dev version of the KVM.

kvm install 1.0.0-alpha4-10353
1. Changed IBuilder to IApplication Builder in the Startup.cs file.

The docs on the ASP.NET site refer to Nuget.config but I couldn't see anything that referred to setting KVM_SOURCE which is where I was struggling. I would add that the alpha3 build does not work for me, I don't know if that is the case with everyone else.

Thanks for the help all the same :-)

**Comment by sayedihashimi** [comment]
Thanks for the details. Should we update [readme.md](https://github.com/ligershark/Kulture/blob/master/README.md)?

@davidfowl @glennc  it would be good if `kpm restore` could pick up on `nuget.config` in the same folder (or in folder with `project.json`). Currently we only have cmd line parameters, which makes it difficult to tool for different nuget repositories. This is especially needed now because we are keeping packages in myget.

Another thing we can consider is to add `KVM_SOURCE` pointing to myget and after we RTM asp.net vNext then remove it. The issue that I see there is that we would also need to set a fallback source to `nuget.org` and I'm not sure if that is available via an env var.

Thoughts?

**Comment by spboyer** [comment]
Should we also update the samples?

**Comment by sayedihashimi** [comment]
OK I did a bit more digging here to better understand what is happening when `kpm restore` is invoked the [`ResolveRootDirectory`](https://github.com/aspnet/KRuntime/blob/069dfb964a86ab505dd6df5e5495434072346b6c/src/Microsoft.Framework.Runtime/ProjectResolver.cs#L65) is called. Here is the if statement that needs to be true for it to pickup on `nuget.config`

``` cs
if (di.EnumerateFiles("*." + GlobalSettings.GlobalFileName).Any() ||
di.EnumerateFiles("*.sln").Any() ||
di.EnumerateDirectories("packages").Any() ||
di.EnumerateDirectories(".git").Any())
```

This was working previously. It broke when we moved the `packages` folder to `%userprofile%`.

@davidfowl @glennc can we take another look at `kpm restore` logic with the xplat case in mind? Is there a better method to discover the "solution root".

To mitigate this we can update the `yo aspnet` generator to drop a `global.json` file in the same directory as `nuget.config`. I've opened [issue 17](https://github.com/ligershark/generator-aspnet/issues/17) to track that.

**Comment by sayedihashimi** [comment]
OK I've made the changes to `yo aspnet` to drop an empty `global.json` file next to `nuget.config`. If you start with that things should work well. After we RTM and all packages get moved to `nuget.config` we can remove that.

**Comment by sayedihashimi** [comment]
With the latest changes I _think_ if you create a new project from `yo aspnet` that `kpm restore` and `kpm build` (including `CMD+B`) should work. I'm inclined to close this since I believe that to be true. I'll leave it open for a few days to see if anyone is still having this issue.

**Comment by matthewblott** [comment]
This can be closed as far as I'm concerned. Thanks.

**Comment by sayedihashimi** [comment]
Thanks @matthewblott I will close this now.

If anyone else is still having this issue for new projects created with `yo aspnet` please reopen with details.

**Comment by justrhysism** [comment]
I just attempted to use the Sample provided with the repo and experienced this exact issue. Please update `Startup.cs` from `IBuilder app` to `IApplicationBuilder app`.
