### ISSUE TITLE
Next meeting

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/Kulture#31]
Hey guys I'd like to see if we can meetup to review all the good work that has progressed this past week, and for us to sync up on our plans going forward. I'm going to be in Vegas next week so I'm hoping we can meet this week.

How is Friday at 10 AM Pacific Time?

I'd like to see if we can get the following folks on the call, but everyone is invited.
@shanselman (optional) @davidfowl @jchannon @nosami @Mpdreamz

If you would like to join but are not listed above please add your Skype user name below.

**Comment by Mpdreamz** [comment]
Works for me :)

**Comment by nosami** [comment]
I can't do Friday evenings (8pm). I'll be travelling home.

**Comment by sayedihashimi** [comment]
OK what about Monday 9/15 at 9:00 AM Pacific Time?

**Comment by jchannon** [comment]
Yup!

**Comment by nosami** [comment]
Is 10:00 AM Pacific Time ok? I'll still be at my day job at 9:00 AM. 

Also, @stephen-james would like an invite. He works with me, and has been working on the Atom plugin. He's also offered to help make any OmniSharpServer changes that are required to move forward.

**Comment by Mpdreamz** [comment]
Monday works for me at 10:00 AM Pacific :+1:

**Comment by jchannon** [comment]
fine for me

**Comment by sayedihashimi** [comment]
OK let's try for 10 AM. I may only be able to attend for 30 minutes because I have to go to the airport, but let's see how it goes.

@stephen-james can you add your skype username below?

**Comment by stephen-james** [comment]
Hey everyone :) 

skype: stephen.hugh.james

**Comment by jchannon** [comment]
OK I've twisted @mat-mcloughlin 's arm and he's going to continue where I left off with Brackets

His skype id is statictony

**Comment by nosami** [comment]
@jchannon @mat-mcloughlin that's fantastic news :)

**Comment by mat-mcloughlin** [comment]
Except thats not my skype name :) its:

live:mathew.mcloughlin

**Comment by sayedihashimi** [comment]
Sorry for the delay here, got back from vacation a few days back and been swamped in emails since.

I just posted the notes from the meeting [on the wiki](https://github.com/ligershark/Kulture/wiki/Meeting---2014.09.15).

I wanted to give you an update on the DTH sample as well. In the next few weeks we are going to be working on a prototype for enabling ASP.NET vNext in Monaco. When we do that we will update DTH to support the scenarios in Monaco. After talking to @davidfowl we think it would make sense to create the DTH sample repo after that. So we will have more info on that in a few weeks.

**Comment by nosami** [comment]
That's great news!

**Comment by jchannon** [comment]
Is the plan to have intellisense etc in the browser for Monaco?

**Comment by sayedihashimi** [comment]
@jchannon we have not yet settled on the initial feature set. I should have more info in a couple of weeks.

**Comment by sayedihashimi** [comment]
Next meeting time proposed at #34.
