### ISSUE TITLE
Next meeting (1st week of October)

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/Kulture#34]
I was wondering if you guys would be interested in meeting up to see how things are going? I'm hoping to setup some time for us to sync up on October 8. We should have more info on the design time host (_and hopefully the sample repo you need_) by this date. Once we have that it should unblock more of the interesting ASP.NET vNext scenarios.

I'll also have some other good news to share that you're likely interested in.

I'd like to see if we can get the following folks on the call, but everyone is invited.
@shanselman @davidfowl @jchannon @nosami @Mpdreamz @stephen-james @mat-mcloughlin

**_How is October 8 at 12:00 PM (_noon_) Pacific Time?**_

**Comment by mat-mcloughlin** [comment]
:( can't make this time. Currently on HST, is that right? on holiday and will likely be up a volcano or something. Can make the 2nd if its some time in the morning PST but don't change it just on my account

**Comment by jchannon** [comment]
I can make it. 8pm UK time I believe

**Comment by nosami** [comment]
I would have been able to make it, but unfortunately by laptop has died :(

**Comment by Mpdreamz** [comment]
Sadly I'm not feeling to well today so I can't make it either.

**Comment by sayedihashimi** [comment]
Sorry guys I got it wrong I was proposing for October 8 not October 1. How is October 8 at 12:00 PM Pacific Time?

I have updated the original issue.

**Comment by nosami** [comment]
Should be fine (assuming I have my laptop back by then)

**Comment by mat-mcloughlin** [comment]
Shoud be good for me too

**Comment by stephen-james** [comment]
Cool, will be there

**Comment by jchannon** [comment]
Yup fine for me!

**Comment by sayedihashimi** [comment]
Hey guys I had a meeting come up which I cannot get out of that conflicts with this. So I cannot make the call today.

Can we move this to **_Friday October 10 at 11 AM Pacific Time**_?

**Comment by nosami** [comment]
I can't do Friday's .... ever! I travel home (200 miles) on Friday evenings.

**Comment by jchannon** [comment]
Fine by me but seeing as Jason can't make it shall we reschedule for some
other time?

**Comment by Mpdreamz** [comment]
Can't do Friday either, maybe layer today?

**Comment by nosami** [comment]
Later today is ok with me.

**Comment by sayedihashimi** [comment]
The rest of my day is full of meetings :( Can we try on **_Monday Oct 13 11 AM Pacific Time**_?

**Comment by jchannon** [comment]
Meetings and deleting emails - we all know thats what you and @shanselman do :smile: 

Monday is fine for me

**Comment by nosami** [comment]
Sure.

**Comment by mat-mcloughlin** [comment]
Me too

**Comment by stephen-james** [comment]
Hey all, afraid am on my way from Barcelona and won't be able to make the meeting

**Comment by sayedihashimi** [comment]
I have started the call, let me know if I should add anyone

**Comment by sayedihashimi** [comment]
Meeting notes at https://github.com/ligershark/Kulture/wiki/Meeting---2014.10.13.
