### ISSUE TITLE
Getting "found project.json in project directory", but nothing after that

### ISSUE THREAD

**Issue by atrauzzi** [ligershark/Kulture#35]
When I do ctrl-shift-p and select "Run K Commands", all I get is the message "found project.json in project directory" at the bottom of the screen.  No menus pop up or anything.

Running on Windows 8, let me know if you need to know anything else.

**Comment by aschlapsi** [comment]
Does your project.json file contain a trailing comma?

Example:

```
"frameworks": {
    "aspnet50" : { },
}
```

**Comment by sayedihashimi** [comment]
If this is still a problem please open a new issue at https://github.com/OmniSharp/Kulture/issues.
