### ISSUE TITLE
-bash: kpm: command not found

### ISSUE THREAD

**Issue by flashfoxter** [ligershark/Kulture#36]
-bash: kpm: command not found

**Comment by sayedihashimi** [comment]
Do you have the [aspnet command line tools](https://github.com/aspnet/home) installed?

**Comment by sayedihashimi** [comment]
If this is still happening please open a new issue at https://github.com/OmniSharp/Kulture/issues.

**Comment by CupSunshine** [comment]
I have solved a same question.It's show "No command 'kpm' found".So i thought  forgot install KRE.
But show "KRE-Mono.1.0.0-beta2 already installed.Cannot find KRE-Mono.1.0.0-beta2,do you need to run ......." when i type "kvm upgrade".Already installed?After,i  had  tried many ways and times.
Finally,i am very sure KRE not be  installed still.But 1.0.0-beta2 can't be installed and uninstalled,how about install 1.0.0-beta1?
Type "kvm install 1.0.0-beta1"   ..........
Success!Haha!
Hope i can help you !
