### ISSUE TITLE
kulture error: Terminal: The terminal terminal was not found in xubuntu

### ISSUE THREAD

**Issue by PauloPhagula** [ligershark/Kulture#43]
I have the error in title on xubuntu

I realize the error is coming from line 90 in Kulture.py whereby default terminal program is assumed to be  _terminal_ when window manager is xfce4.

``` python
elif wm[0] == 'xfce4-session':
    default = 'terminal'
elif wm[0] == 'ksmserver':
```

In my case I'm running Xubuntu with no particular changes to system and default terminal program is xfce terminal.

**Comment by sayedihashimi** [comment]
I have moved the issue to https://github.com/OmniSharp/Kulture/issues/7. Let's continue the discussion there.

_I am going to be moving everything to that new repo this weekend hopefully._
