### ISSUE TITLE
Are there plans to port this to dnx?

### ISSUE THREAD

**Issue by swaggerloaf** [ligershark/Kulture#45]
curious if anyone is working that

**Comment by shanselman** [comment]
Yes, but not yet. Feel free to help

On Wed, Mar 11, 2015 at 11:52 AM, Swagger of the loaf kind <
notifications@github.com> wrote:

> curious if anyone is working that
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ligershark/Kulture/issues/45.

## 

Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by sayedihashimi** [comment]
Hey guys this is the wrong repo the new repo is at https://github.com/OmniSharp/Kulture/. Closing this here.
