### ISSUE TITLE
kpm restore does nothing

### ISSUE THREAD

**Issue by islamath** [ligershark/Kulture#6]
Hi there!

I just followed the instructions you gave , but when i do ctrl+shift+p > run k commands > kpm   restore! it does not open the terminal window as described

Plz Help

**Comment by shirhatti** [comment]
Can your press `Ctrl + ~` to open the Sublime Console and post the errors you receive if any

**Comment by islamath** [comment]
Nothing special is tailing in the console

reloading plugin Package Control.Package Control
reloading plugin Kulture.Kulture
plugins loaded
Package Control: No updated packages

**Comment by islamath** [comment]
Ok!

That's weird :s!! when i opened the Kulture.py file with sublime & did ctrl+shift+p > run k commands > kpm restore! it magically worked :)

Have no clue why?

Anyway! Closed
