### ISSUE TITLE
Nancy

### ISSUE THREAD

**Issue by jchannon** [ligershark/Kulture#7]
Just to let you know I've taken your aspnet generator and made a Nancy one https://www.npmjs.org/package/generator-nancy

Please try it out and let me know how it goes

**Comment by shirhatti** [comment]
Just tried it out :thumbsup: 
I'm bringing more features to the yo-generator, you can follow that at https://github.com/shirhatti/generator-aspnet

**Comment by jchannon** [comment]
Cool! Maybe we can combine them if interested?

**Comment by sayedihashimi** [comment]
@shanselman Scott, do you think we should combine aspnet and aspnet nancy generators into a single generator or keep them separate?

**Comment by shanselman** [comment]
Well, it depends on how big this gets. It'd be nice if it had a lot of choices out of the box, but a simple plugin model would be more flexible.

**Comment by jchannon** [comment]
I'll leave this here https://www.youtube.com/watch?v=qZDRhNw_TPI

This is a great plugin, good work chaps!

**Comment by shirhatti** [comment]
@shanselman @jchannon  We can consider a few basic templates and one option that says show me more options. Allow the community to contribute to this list the power the more options.

Eg:

```
[?] What type of application do you want to create? (Use arrow keys)
> Console Application
   Web Application
   MVC Application
   Show me more templates
```

The show me more templates will be powered by a JSON file that folks can contribute to easily.
Eg: https://github.com/shirhatti/package_control_channel/blob/master/repository/f.json

``` json
[
  {
    "name": "Nancy",
    "description": "Nancy ASP.NET App generator",
    "url": "https://github.com/jchannon/aspnet_vnext_samples"
  },
  {
    "name": "Another awesome generator",
    "description": "Make awesome apps",
    "url": "http://awesomeliveshere"
  }
]
```

**Comment by sayedihashimi** [comment]
The proposal from @Shirhatti sounds good to me.

**Comment by jchannon** [comment]
How about if you had? 

```
[?] What type of application do you want to create? (Use arrow keys)
> Console Application
  > Nancy
    SimpleWeb
    WebAPI
    etc
   Web Application
    Nancy
    SimpleWeb
    WebAPI
    etc
```

**Comment by sayedihashimi** [comment]
I think that is going to lead to too many options in the long run. Also if we did want to try that can we point to the separate repo easily like in the Try More case or would they have to be in the same repo?

**Comment by jchannon** [comment]
We could point to the seperate repo a bit like this - https://github.com/shirhatti/generator-aspnet/blob/master/app/index.js#L72

**Comment by sayedihashimi** [comment]
OK let's try it out if we get to the point where there are too many options then we can simplify after that. We should make sure that all templates are working with significant releases of VS.

cc @shirhatti @shanselman

**Comment by jchannon** [comment]
Cool :balloon: 

I'm not sure what other options you're thinking of though. SW and Fubu are no longer being maintained. OpenRasta is starting up again so that might be one option. I guess there may be a F# option too that people may like?

**Comment by sayedihashimi** [comment]
@jchannon we are planning to write a blog post on the [asp.net web dev blog](http://blogs.msdn.com/b/webdev/) for the generators soon. Ideally we could include the Nancy generators in that post as well. Did you want to put together the PR for the changes required to include the Nancy generators? If you can get it in the next few days I can release and @shirhatti can update the post.

**Comment by jchannon** [comment]
Yup I'll get that done today!

**Comment by jchannon** [comment]
Done - https://github.com/ligershark/generator-aspnet/pull/12

**Comment by sayedihashimi** [comment]
OK Nancy generators are now a part of asp.net generators, I will close this item now.
