### ISSUE TITLE
Running `k kestrel` doesn't open Powershell and start

### ISSUE THREAD

**Issue by jchannon** [ligershark/Kulture#8]
Running `k kestrel` doesn't open Powershell on Windows and start but if I manually run `k kestrel` it shows `Started` from cmd prompt and I can see content in a browser

**Comment by shirhatti** [comment]
Can your press `Ctrl + ~` to open the Sublime Console and post the errors you receive if any

**Comment by jchannon** [comment]
Doesn't log anything to sublime console

**Comment by jchannon** [comment]
Fixed in latest build
