### ISSUE TITLE
Debugging support

### ISSUE THREAD

**Issue by jchannon** [ligershark/Kulture#9]
Is there a plan to get debugging working?

**Comment by sayedihashimi** [comment]
We could make a plan together :) I think we should prioritize #12 c# IntelliSense before debugging though.

We are currently looking for help so of you are interested in either that would be great.

cc @Shirhatti @shanselman

**Comment by sayedihashimi** [comment]
Does sublime debugging work for any other fx/language? Trying to see if there is a precedent for this.

**Comment by jchannon** [comment]
I think its a case of having plugins that attach to debuggers for example PHP and Xdebug - http://www.sitepoint.com/debugging-xdebug-sublime-text-3/

**Comment by sayedihashimi** [comment]
Kulture is moving to a new home at https://github.com/OmniSharp/Kulture.

Closing this now. Let's discuss this there if needed.
